---
#
# Playbook deploying and setting up your undercloud for overcloud deployment in scale lab
# environment or the bagl environment.
#
# Tested against OSP 8/9/10 and single-nic-vlans config setup with private external network
#

- name: Run initial setup tasks
  hosts: undercloud
  gather_facts: true
  remote_user: root
  roles:
    - rebuild-undercloud
    - undercloud-prepare-host

- name: Run OSP install
  hosts: undercloud
  gather_facts: false
  remote_user: stack
  roles:
    - undercloud-install
    - overcloud-prepare-templates
    - overcloud-deploy
    - scalelab-network
    - scalelab-inventory

- name: Setup Overcloud Metrics Controller and Ceph
  hosts: controller:cephstorage
  vars:
    - config_type: "{{group_names[0]}}"
  roles:
    - browbeat/common
    - browbeat/osp_version
    - browbeat/epel
    - browbeat/collectd-openstack
    - browbeat/rsyslog-install
    - browbeat/rsyslog-templates

- name: Setup Overcloud Metrics Compute
  hosts: compute
  roles:
    - browbeat/common
    - browbeat/osp_version
    - browbeat/epel
    - browbeat/rsyslog-install
    - browbeat/rsyslog-templates
