---

- name: Ensure gather_facts has been run against localhost
  setup:
  delegate_to: localhost
  delegate_facts: True
  when: hostvars['localhost'].ansible_user_dir is not defined

- name: Ensure gather_facts has been run against undercloud
  setup:

#required for liberty based deployments
- name: copy get-overcloud-nodes.py to undercloud
  template:
    src: 'get-overcloud-nodes.py.j2'
    dest: '{{ working_dir }}/get-overcloud-nodes.py'
    mode: 0755

#required for liberty based deployments
- name: fetch overcloud node names and IPs
  shell: >
      source {{ working_dir }}/stackrc;
      python {{ working_dir }}/get-overcloud-nodes.py
  register: registered_overcloud_nodes

- name: list the overcloud nodes
  debug: var=registered_overcloud_nodes.stdout

- name: fetch the undercloud ssh key
  fetch:
    src: '/home/stack/.ssh/id_rsa'
    dest: '{{ overcloud_key }}'
    flat: yes
    mode: 0400

#required for regeneration of ssh.config.ansible
- name: set_fact for undercloud ip
  set_fact:
    undercloud_ip: "{{ ansible_default_ipv4.address }} "

#required for regeneration of ssh.config.ansible
- name: set undercloud ssh proxy command
  set_fact:
    undercloud_ssh_proxy_command: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
      -o ConnectTimeout=60 -i {{ overcloud_key }}
      {{ ssh_user }}@{{ hostvars['localhost'].ansible_default_ipv4.address }}
      -W {{ undercloud_ip }}:22"

# add host to the ansible group formed from its type
# novacompute nodes are added as compute for backwards compatibility
- name: add overcloud node to ansible
  with_dict: '{{ registered_overcloud_nodes.stdout | default({}) }}'
  add_host:
    name: '{{ item.key }}'
    groups: "overcloud,{{ item.key | regex_replace('overcloud-(?:nova)?([a-zA-Z0-9_]+)-[0-9]+$', '\\1') }}"
    ansible_host: '{{ item.key }}'
    ansible_fqdn: '{{ item.value }}'
    ansible_user: "{{ overcloud_user | default('heat-admin') }}"
    ansible_private_key_file: "{{ overcloud_key }}"
    ansible_ssh_common_args: ' -F {{local_working_dir}}/ssh.config.ansible'

- name: create inventory from template
  template:
    src: 'inventory.j2'
    dest: '{{working_dir}}/hosts'

- name: regenerate ssh config
  template:
    src: 'ssh_config.j2'
    dest: '{{working_dir}}/ssh.config.ansible'
    mode: 0644

- name: Fetch hosts
  fetch:
    flat: yes
    src: "{{working_dir}}/hosts"
    dest: "{{local_working_dir}}/hosts"

- name: Fetch ssh config
  fetch:
    flat: yes
    src: "{{working_dir}}/ssh.config.ansible"
    dest: "{{local_working_dir}}/ssh.config.ansible"

# just setup the ssh.config.ansible and hosts file for the undercloud
- name: check for existence of identity key
  delegate_to: localhost
  stat: path="{{overcloud_key}}"
